version: '3.8'

services:
  app:
    build:
      context: .         # Verweis auf das aktuelle Verzeichnis, wo die Dockerfile liegt
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - API_SECRET=${API_SECRET} # Liest die Umgebungsvariable aus .env oder Coolify
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`https://pgw4kwgocs4804kowsso8o4c.coolify.dt-e.eu`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.app.loadbalancer.healthcheck.interval=10s"