version: '3.8'

services:
  app:
    build:
      context: .         # Verweis auf das aktuelle Verzeichnis, wo die Dockerfile liegt
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - API_SECRET=${API_SECRET} # Liest die Umgebungsvariable aus .env oder Coolify
    ports:
      - "3000:3000"
